Bit-Quill/aws-mysql-jdbc

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/MultiThreadedDefaultMonitorServiceTest.java

Unit tests calling `DefaultMonitorService#startMonitoring` in a multi-threaded environment.
- No tests for `stopMonitoring` at the moment since it is very straightforward.
```java
public void stopMonitoring(MonitorConnectionContext context) {
final IMonitor monitor = this.threadContainer.getMonitorMap().get(context.getNodeKeys().iterator().next());
monitor.stopMonitoring(context);
}
```
- Tests for `NodeMonitorFailoverPlugin#execute` will be in a separate PR.
- Repeats each test multiple times.
- Use cyclic barrier in threads to ensure threads start at the same time.
@brunos-bq 
@ColinKYuen

Multithreaded tests for DefaultMonitorService

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultFailoverPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/FailoverPluginManager.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionProvider.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IFailoverPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitorService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/Monitor.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorThreadContainer.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPluginFactory.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/MultithreadedNodeMonitoringFailoverPluginTest.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPluginBaseTest.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPluginTest.java

feat: Pass ClusterAwareConnectionProxy to failover plugins so they can use are using the most up-to-date connection.
https://bitquill.atlassian.net/browse/RDS-475
After a failover has occurred, a new connection will be set in `ClusterAwareConnectionProxy`.
To let the `NodeMonitoringFailoverPlugin` know there is a new connection, we have to release the resources and reinitialize the plugin. This creates a lot of overhead when there are only 2 things the need to be updated:
1. connection
2. host info
This change removes the need to restart the monitoring plugin.
The `ClusterAwareConnectionProxy` implements `IConnectionProvider` which contains methods to retrieve the new connection. Plugins maintain a reference to the proxy, and whenever the connection or host info is required, call …

Update plugins with most recent connection

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorThreadContainer.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/MultiThreadedDefaultMonitorServiceTest.java

test: Add multi-threaded tests for `DefaultMonitorService#stopMonitoring`
- simplify methods for running multi-threaded tests
- add 2 tests for stopMonitoring
https://bitquill.atlassian.net/browse/RDS-503
@matthewh-BQ 
@brunos-bq 
@ColinKYuen

test: Add multi-threaded tests for stop monitoring.

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPlugin.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPluginTest.java

Potential NPE by user in NodeMonitoringFailoverPlugin fix
Fixing a potential issue when user updates the propertySet `nativeFailureDetectionEnabled`
Starting from Disabled -> Enabled, would NOT initialize the `monitorServiceInitializer` then later try to use it.
Starting from Enabled -> Disabled, would skip the direct call and proceed with the monitoring.
- Moved checking of updated propertySet before checking to do direct calls.
- Added null check for initializer and create if null inside execute()
@karenc-bq 
@matthewh-BQ 
@brunos-bq

Potential NPE by user in NodeMonitoringFailoverPlugin

---

build.gradle.kts
src/main/resources/META-INF/services/java.sql.Driver
src/test/java/testsuite/regression/ConnectionRegressionTest.java

Fix hanging tests in GitHub Actions
- Check to ensure Driver is not registered in `testBug69579()` which fixes test.
- Disabled `testBug73053()` which tests fix for endless loop due to Linux Kernel bug.
- Added setting of loginTimeout after tests to original value.

fix: Hanging tests

---

src/test/java/testsuite/regression/ConnectionRegressionTest.java

#39 Finds the hanging test and fixes the failing test `testBug69579`.
This PR investigates why the test is hanging.
`testBug73053` hangs on Github Actions when it is attempting to close the test connection, but passes just fine locally. This is because the remote environment uses `TLSv1.3`.
When closing a connection, if `TLSv1.3` is used, the driver roughly follows this workflow: 
```
SSLSocketImpl#duplexCloseOutput -> SSLSocketImpl#bruteForceCloseInput(false) -> SSLSocketInputRecord#deplete
```
and it gets stuck in an infinite loop in `SSLSocketInputRecord#deplete`
```Java
while ((remaining = is.available()) != 0) {
is.skip(remaining);
}
```
This method uses a custom `InputStream` implemented for `testBug73053`: `TestBug73053InputStreamWrapper`, where `is.available()` [will never return …

Debug hanging test

---

.github/workflows/release.yml

Release Process Automation
Updated workflow for `release` to be able to use GPG keys with passphrase.
GPG Private key stored in GitHub Actions, `GPG_PRIVATE_KEY`
Private Key Passphrase stored in GitHub Actions, `GPG_PASSPHRASE`
@karenc-bq

chore: Updated to allowed GPG with passwords

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorConnectionContext.java

Removed condition of adjustedFailureCount
MonitorConnectionContext does NOT need the extra check of adjustedFailureCount.
The condition for checking (failureCount >= adjustedFailureCount) is always going to be hit before or at the same time the other condition of (invalidNodeDuration >= maxInvalidNodeDuration).
In the current implementation, since both cases need to be true for the context to be considered unhealthy, it is not needed.
In the case of letting either condition being hit to consider a context as unhealthy, then given the following parameters
- validationInterval = 300
- failureDetectionTime = 10
- failureDetectionInterval = 100
- failureDetectionCount = 2
This would trigger off the condition of (failureCount >= adjustedFailureCount) as soon as it hits the first failureCount …

refactor: Removed condition of adjustedFailureCount

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/MultiHostConnectionProxy.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/ConnectionPluginManager.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/MultithreadedNodeMonitoringConnectionPluginTest.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginBaseTest.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginTest.java

FailoverPluginManager.execute() Method Signature Changes
FailoverPluginManager.execute() method signature currently lacks identifiability to other class’ execute() methods. Adding interface name to method signature can help uniquely identify it from others.
@matthewh-BQ 
@karenc-bq 
@ColinKYuen 
@brunos-bq

Rds-516 method signature

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java

Do not monitor `ResultSetImpl::next`.
https://bitquill.atlassian.net/browse/RDS-554
It is still uncertain why monitoring `next` would result in driver unable to finish execution; however, the implementation of `next` does not make any calls to the server, so we shouldn't need to monitor it.
@ColinKYuen

fix: add `next` to list of methods not requiring monitoring

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java

refactor: Simplifying Supplier Lambda
Moved supplier lambda into method parameter.
For "clearing contexts when doing failover", it should still do this based on the latest changes in No-threads #62 as when a failover occurs, the connection is aborted.
@karenc-bq @sergiyv-bitquill @matthewh-BQ

refactor: Simplifying Supplier Lambda

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorThreadContainer.java

MonitorThreadContainer executor get/release
- Use of object locks instead of synchronizing whole method block for getting and releasing singleton MonitorThreadContainer.
- Added null check for Monitor in `releaseResource(IMonitor monitor)`.
@karenc-bq

refactor: MonitorThreadContainer get/release

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/AuroraTopologyService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandler.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareUtils.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareWriterFailoverHandler.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/ConnectionPluginManager.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitor.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitorService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/Monitor.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorConnectionContext.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorThreadContainer.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginFactory.java
src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandlerTest.java
src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareTestUtils.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorServiceTest.java
src/test/java/testsuite/failover/ReplicationFailoverIntegrationTest.java

Address warnings reported by the Checkstyle plugin.
Only warnings remaining are related to missing Javadoc, which will be added in a separate PR.
Types of warnings addressed:
- wrong indentation level
- missing whitespaces
- missing ending period in Javadoc comment.
@ColinKYuen 
@matthewh-BQ

Address checkstyle warnings

---

config/checkstyle/checkstyle.xml
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandler.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareUtils.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/TopologyService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/ConnectionPluginManager.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/ICurrentConnectionProvider.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IExecutorServiceInitializer.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitor.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitorInitializer.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitorService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/Monitor.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorConnectionContext.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorThreadContainer.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginFactory.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NullArgumentMessage.java
src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorConnectionContextTest.java

Add missing Javadoc reported by the checkstyle plugin.
Will selectively add more Javadoc in important/complex code paths in a different PR.
- Remove unused parameter in `MonitorConnectionContext`
- Fix a missing change lost during rebase.
@ColinKYuen 
@matthewh-BQ

Add Javadoc (part 1) and extra fixes

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPlugin.java

Fixes failover integration test failures
Issue was caused by catching `InvocationTargetException` inside `DefaultConnectionPlugin` and then casting it to a generic `Exception`. This caused issues when the driver was trying to intercept the exception but was not able to get the correct information due to the cast.
@karenc-bq @sergiyv-bitquill

fix: Integration test

---

build.gradle.kts
src/test/java/com/mysql/cj/jdbc/NonRegisteringDriverTest.java
src/test/java/com/mysql/cj/jdbc/SQLXMLTests.java

Remove outdated JBoss dependency with `org.javassist:javassist`
Build scan: https://scans.gradle.com/s/chrjkbwpxpr3k
- Replace `jboss-as-connector` dependency from 2011 with a more specific and up-to-date dependency `javassist`
- Fix Assertion imports in tests
@matthewh-BQ 
@ColinKYuen

Remove JBoss dependency

---

build.gradle.kts
gradle.properties
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
src/test/java/testsuite/failover/NetworkFailuresFailoverIntegrationTest.java

Fix Network Failures Failover Integration Test 
Related Ticket: [389](https://bitquill.atlassian.net/browse/RDS-389)
- Updated params for db connection
- Removed two releaseResources() causing NPE
- Reduced `failoverTimeoutMs` for `test_1_LostConnectionToWriter` to 10,000 (10s) rather than using default of 300,000 (5m). This was causing it to ""hang"".
Removed the following as they are no longer used
- systemProp.com.mysql.cj.testsuite.failover.networkFailures.clusterEndpointBase
- systemProp.com.mysql.cj.testsuite.failover.networkFailures.clusterName
- systemProp.com.mysql.cj.testsuite.failover.networkFailures.database
- systemProp.com.mysql.cj.testsuite.failover.networkFailures.user
- systemProp.com.mysql.cj.testsuite.failover.networkFailures.password
@karenc-bq @sergiyv-bitquill …

fix: NetworkFailuresFailoverIntegrationTest

---

README.md
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/ConnectionPluginManager.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java
src/main/user-impl/java/software/aws/rds/jdbc/mysql/Driver.java

Use daemon threads to monitor failure.
|           | Average Execution Time (s) |        | Warmup Time vs. Community |
|-----------|----------------------------|--------|---------------------------|
|           | No Warmup                  | Warmup |                           |
| Community | 0.022                      | 0.019  | 0.00%                     |
| Introspection  | 0.04                       | 0.037  | 94.74%                    |
| Daemon    | 0.03                     | 0.027   | 42.11%                   |
|           | Average Execution Time (s) |        | Warmup Time vs. Community |
|-----------|----------------------------|--------|---------------------------|
|           | No Warmup                  | Warmup |                           |
| Community | 5.172 …

refactor: run monitoring threads as daemon threads

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandler.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ITopologyService.java
src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java

Propagate SQL exception from queryTopology
Propagate SQL exception from queryTopology so it can be handled by caller instead of ignoring the exception
@ColinKYuen

Propagate SQL exception from queryTopology

---

.github/workflows/main.yml

Workflow manual trigger
Workflow can now be manually triggered by going to Actions -> CI -> Run Workflow
@sergiyv-bitquill @karenc-bq @crystall-bitquill

chore: Workflow manual trigger

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/Monitor.java
src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/MonitorConnectionContext.java
src/test/java/com/mysql/cj/jdbc/ha/plugins/MonitorConnectionContextTest.java
src/test/java/testsuite/integration/host/AuroraIntegrationContainerTest.java

RDS-623: MySQL - JDBC - Verify EFM plugin for number of failures before raising exception.
EFM plugin waits one failure interval more than expected.
@ColinKYuen 
@karenc-bq 
@crystall-bitquill 
@matthewh-BQ

fix the bug: adjust allowed failure time

---

src/main/core-api/java/com/mysql/cj/conf/PropertyKey.java
src/test/java/testsuite/integration/container/AuroraMysqlPerformanceIntegrationTest.java

MySQL - JDBC - Add integration performance tests for failover
Add failover integration performance tests. Tests measure failover with 1) socketTimeout 2) EFM
@karenc-bq 
@ColinKYuen 
@hsuamz 
@crystall-bitquill

implement failover performance tests

---

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java

Update host index before updating hosts
During failover, the current host index was being updated after updating the hosts. The current host index was incorrect because it used the the latest topology and the old host index rather than the old topology and old host index in the `updateHostIndex(List<HostInfo> latestTopology)` function.
@sergiyv-bitquill @karenc-bq @ColinKYuen

Update host index before updating hosts

---

.github/workflows/pull_request.yml
src/test/java/testsuite/integration/container/AuroraMysqlIntegrationTest.java
src/test/java/testsuite/integration/utility/AuroraTestUtility.java

Allow Forked PR to run CI
Allow forked PRs to use secrets through environment. CI from PRs will now need to be approved before running.
Disabled `test_ClusterEndpointReadOnlyFailover`. Often fails due to connecting to a writer instance when using Read-only cluster URL.

chore: Allow Forked PR to run CI

---

.github/workflows/pull_request.yml

Remove Integration Tests from PR Triggers
Removes integration tests from PRs as there is no safe way to access secrets which would be used to authenticate the runner.

chore: Remove Integration Tests from PR Triggers
