src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultFailoverPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultFailoverPluginFactory.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/FailoverPluginManager.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IFailoverPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPluginFactory.java
Reformat code
@sergiyv-bitquill
=> chore: Reformat code

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringFailoverPlugin.java
fix: Only query for hostname if we have a new connection
Currently, every time users attempts to execute a query the driver issues a query to retrieve the hostname for the current connection.
There is a delay after failover occurs where the `ClusterAwareConnectionProxy` hasn't updated its reference to the new connection yet.
When user attempts to execute a query during this time, the driver will send another query looking for the current host before actually executing the query. This earlier query will fail due a communication link exception, causing the `Statement` object to clear its reference to a connection object.
When failover finish and the connection has been updated, because `Statement` no longer has a reference to the connection object, it assumes the connection has closed and …
=> fix: Only query for hostname if we have a new connection

.github/workflows/introspection.yml, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java, src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/MultithreadedNodeMonitoringFailoverPluginTest.java
Add Github Actions workflow for `introspection` branch, running tests in `"com.mysql.cj.jdbc.*"` and fix flaky multithreaded test.
@ColinKYuen 
@brunos-bq
=> Add workflow to introspection branch and bug fix

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/FailoverPluginManager.java
Ensure Monitor Resources Cleanup
Added more areas to release the Plugin Manager's resources. Particularly when failover fails or when the connection proxy is closed explicitly.
@karenc-bq
@sergiyv-bitquill
@hsuamz
=> Ensure Plugin Manager Resources Cleanup

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/Monitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java
Check if Monitor Requires Additional Properties
Provide a way to supply monitoring connection with a custom set of configuration properties.
@karenc-bq 
@ColinKYuen 
@brunos-bq 
@matthewh-BQ 
@yanw-bq
=> provide configuration parameters to a monitoring connection

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java
Remove excessive logging in hot path
Improves the performance when iterating over large result sets by 71%
@matthewh-BQ 
@ColinKYuen 
@sergiyv-bitquill
=> Remove logs

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java, src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginBaseTest.java, src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginTest.java
Changed functional interfaces to suppliers
- Changed functional interfaces to suppliers.
- Updated test to reflect changes.
@karenc-bq
=> refactor: use supplier instead of functional interface

src/main/core-api/java/com/mysql/cj/conf/PropertyDefinitions.java, src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/ConnectionPluginManager.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultConnectionPluginFactory.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IConnectionPluginFactory.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/Monitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginFactory.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NullArgumentException.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NullArgumentMessage.java, src/test/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPluginTest.java
Simplified NullArgumentException
- Changed to only generate message
- Places where NullArgumentException used to throw replaced to throw RuntimeException with the message generated from NullArgumentException
- Added missing statements that disappeared during rebase/merge
@karenc-bq 
@matthewh-BQ
=> refactor: Simplified NullArgumentException

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareWriterFailoverHandler.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ReaderFailoverResult.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/DefaultMonitorService.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/IMonitorService.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/Monitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/MonitorConnectionContext.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/plugins/NodeMonitoringConnectionPlugin.java
Add more Javadoc to some non-public methods
@ColinKYuen 
@matthewh-BQ
=> Add more Javadoc

src/main/user-impl/java/com/mysql/cj/jdbc/ha/MultiHostConnectionProxy.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
Revert locks
Reverts changes of #58 
@karenc-bq @matthewh-BQ @sergiyv-bitquill
=> Revert locks

src/demo/java/customplugins/ExecutionTimeConnectionPlugin.java, src/demo/java/customplugins/MethodCountConnectionPlugin.java, src/demo/java/customplugins/README.md, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxyLifecycleInterceptor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ConnectionPluginManager.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/DefaultConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/IConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ITransactionContextHandler.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
Propagate transaction information to the plugins
@ColinKYuen 
@matthewh-BQ
=> Lifecycle interceptor refactor

src/demo/java/customplugins/ExecutionTimeConnectionPlugin.java, src/demo/java/customplugins/MethodCountConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ConnectionPluginManager.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/DefaultConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/DefaultConnectionPluginFactory.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/IConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java, src/test/java/com/mysql/cj/jdbc/ha/ConnectionProxyTest.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPluginTest.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
MySQL - JDBC - Optimization - Extend Plugin Interface for Initial Connection Method
@karenc-bq 
@ColinKYuen
=> create initial connection

src/test/java/testsuite/regression/BlobRegressionTest.java, src/test/java/testsuite/regression/PooledConnectionRegressionTest.java, src/test/java/testsuite/regression/StatementRegressionTest.java
Enable tests that would crash Gradle when ran locally.
=> Enable tests

.github/workflows/main.yml
Optimize workflow
- Rather than using a hardcoded 20m sleep, using aws api to check instance status.
- Run actions only when approved or pushed/merged into main
@karenc-bq @sergiyv-bitquill @crystall-bitquill @matthewh-BQ
=> chore: Optimize workflow

README.md, src/main/core-api/java/com/mysql/cj/conf/PropertyDefinitions.java
Update README and edit property definition
- Changed property enableClusterAwareFailover to be runtime modifiable
- Added Failover plugin section to README
- Edited README to be clearer
@karenc-bq @ColinKYuen @sergiyv-bitquill
=> Update README and edit property definition

.github/workflows/main.yml, build.gradle.kts, src/test/java/testsuite/integration/host/AuroraIntegrationContainerTest.java, src/test/java/testsuite/integration/utility/AuroraTestUtility.java
Aurora Integration Test Utilities
Creation and destruction of RDS Cluster/Instances are now done using the Java SDK rather than inside GitHub Actions AWS CLI. This includes whitelisting and delisting the current IP address.
=> Aurora Integration Test Utilities

src/test/java/testsuite/integration/ClusterPerfMetricIntegrationTest.java, src/test/java/testsuite/integration/container/AuroraMysqlIntegrationTest.java, src/test/java/testsuite/integration/host/AuroraIntegrationContainerTest.java, src/test/java/testsuite/integration/host/CommunityContainerTest.java, src/test/java/testsuite/integration/utility/AuroraTestUtility.java, src/test/java/testsuite/integration/utility/ContainerHelper.java
Fix probable bugs found by static analysis
- Changed test container names
- Changed finding strings from streams to conditionals
@karenc-bq @ColinKYuen
=> Fix probable bugs found by static analysis

README.md, src/main/user-impl/java/software/aws/rds/jdbc/mysql/Driver.java
Merge with AWS Upstream
Merge with AWS Upstream & slight doc change for integration testing steps
@sergiyv-bitquill @matthewh-BQ @karenc-bq @crystall-bitquill
=> Merge with AWS Upstream

CHANGELOG.md, gradle.properties
Changelog update
Updating the changelog to reflect changes & updating versioning to 1.0.0
Readme won't be updated as Susan already has a PR on that.
@matthewh-BQ @sergiyv-bitquill @karenc-bq @crystall-bitquill
=> Update changelog and versioning

.github/workflows/main.yml, build.gradle.kts, src/test/java/testsuite/integration/container/AuroraMysqlFailoverIntegrationTest.java, src/test/java/testsuite/integration/container/AuroraMysqlIntegrationBaseTest.java, src/test/java/testsuite/integration/container/AuroraMysqlIntegrationTest.java, src/test/java/testsuite/integration/container/IntegrationTestSuite.java, src/test/java/testsuite/integration/host/AuroraIntegrationContainerTest.java, src/test/java/testsuite/integration/utility/AuroraTestUtility.java, src/test/java/testsuite/integration/utility/ContainerHelper.java
test: Improve flakey tests
- Tagging cluster, for maint window to auto delete
- Test ordering. Network > Hard
- Masking session token
- Query for ID rather than use SDK
- Moved test clusterEndpoint to AuroraIntegration
@karenc-bq @crystall-bitquill @sergiyv-bitquill @matthewh-BQ
=> test: Improve flakey tests

.github/workflows/pull_request.yml
Fix GitHub Actions Environment
Change from name -> env
=> chore: Fix GitHub Actions Environment
